Update example for Variants with many values
ben-rogerson/twin.macro pull request #427
Opened 2021-05-05 14:18 UTC by vinamelody

Updating the example snippet based on
https://github.com/ben-rogerson/twin.macro/discussions/425

2021-05-06 21:08 UTC, ben-rogerson requested changes
Just a small grammar fix, looks great otherwise - thanks :)

2021-05-06 21:08 UTC, ben-rogerson commented on docs/styled-component-guide.md
> +When a variant has many values (eg: `variant="light/dark/etc"`), name the class set in an object and use a prop to grab the entry containing the styles. Note that you must return a function as follow
Grammar fix:

```suggestion
When a variant has many values (eg: `variant="light/dark/etc"`), name the class set in an object and use a prop to grab the entry containing the styles. Note that you must return a function as follows:
```

2021-05-07 08:33 UTC, vinamelody commented on docs/styled-component-guide.md
> +When a variant has many values (eg: `variant="light/dark/etc"`), name the class set in an object and use a prop to grab the entry containing the styles. Note that you must return a function as follow
Sure, thanks for the review 👍

2021-05-07 12:29 UTC, merged

2021-05-07 12:29 UTC, ben-rogerson commented
thanks again 👋

2021-05-07 14:36 UTC, vinamelody commented
^^ I'm the one who needs to thank you!